custom:
  layerConfig:
    installLayers: false
  capacities:
    - table: afreehpLogTable
      read:
        minimum: 5
        maximum: 100
        usage: 0.6
      write:
        minimum: 5
        maximum: 100
        usage: 0.5