custom:
  layerConfig:
    installLayers: false
  capacities:
    - table: afreehpLogTable
      read:
        minimum: 20
        maximum: 500
        usage: 0.5
      write:
        minimum: 20
        maximum: 500
        usage: 0.5
