service: afreehp-api

# provider 설정
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-2
  architecture: arm64
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - apigateway:ManageConnections
        - execute-api:ManageConnection
      Resource: 'arn:aws:execute-api:ap-northeast-2:*:*'
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: 'arn:aws:sqs:ap-northeast-2:*:*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
      Resource: 'arn:aws:dynamodb:ap-northeast-2:*:*'

# plugins 설정
plugins:
  - serverless-plugin-layer-manager
  - serverless-lift

# functions 설정
functions:
  app:
    handler: handler/app.handler
    timeout: 10
    environment: ${file(env.js)}
    events:
      - httpApi: '*'
  event:
    handler: handler/event.handler
    timeout: 10
    environment: ${file(env.js)}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - afreehpEventQueue
              - Arn
  connect:
    timeout: 5
    handler: handler/websocket.connect
    environment: ${file(env.js)}
    events:
      - websocket:
          route: $connect
  disconnect:
    timeout: 5
    handler: handler/websocket.disconnect
    environment: ${file(env.js)}
    events:
      - websocket:
          route: $disconnect
  message:
    timeout: 10
    handler: handler/websocket.message
    environment: ${file(env.js)}
    events:
      - websocket:
          route: $default

# resources 설정
resources:
  Resources:
    afreehpEventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: afreehpEventQueue.fifo
        FifoQueue: true
        MessageRetentionPeriod: 86400
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 60
    afreehpTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: afreehp
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

# constructs 설정
constructs:
  website:
    type: server-side-website
    domain: afreehp.dochis.net
    certificate: arn:aws:acm:us-east-1:048901423835:certificate/a4b11e86-a541-4bae-bd2c-56cab6c0a7dc
    assets:
      '/app/**': public/app
      '/assets/**': public/assets

# package 설정
package:
  exclude:
    - .github/**
    - public/**