service: afreehp-api

# provider 설정
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-2
  architecture: arm64
  memorySize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - apigateway:ManageConnections
        - execute-api:ManageConnection
      Resource: 'arn:aws:execute-api:ap-northeast-2:*:*'
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: 'arn:aws:sqs:ap-northeast-2:*:*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
      Resource: 'arn:aws:dynamodb:ap-northeast-2:*:*'

# plugins 설정
plugins:
  - serverless-dynamodb-autoscaling
  - serverless-plugin-layer-manager
  - serverless-lift

# functions 설정
functions:
  app:
    timeout: 10
    handler: handler/app.handler
    environment: ${file(env.${opt:stage, self:provider.stage}.js)}
    events:
      - httpApi: '*'
  connect:
    timeout: 10
    handler: handler/websocket.connect
    environment: ${file(env.${opt:stage, self:provider.stage}.js)}
    events:
      - websocket:
          route: $connect
  disconnect:
    timeout: 10
    handler: handler/websocket.disconnect
    environment: ${file(env.${opt:stage, self:provider.stage}.js)}
    events:
      - websocket:
          route: $disconnect
  message:
    timeout: 20
    handler: handler/websocket.message
    environment: ${file(env.${opt:stage, self:provider.stage}.js)}
    events:
      - websocket:
          route: $default
  logger:
    timeout: 5
    handler: handler/logger.handler
    environment: ${file(env.${opt:stage, self:provider.stage}.js)}
    events:
      - cloudwatchLog:
          logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-app
          filter: '[timestamp=*Z, request_id="*-*", event]'
      - cloudwatchLog:
          logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-connect
          filter: '[timestamp=*Z, request_id="*-*", event]'
      - cloudwatchLog:
          logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-disconnect
          filter: '[timestamp=*Z, request_id="*-*", event]'
      - cloudwatchLog:
          logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-message
          filter: '[timestamp=*Z, request_id="*-*", event]'

# resources 설정
resources:
  Resources:
    afreehpTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: afreehp-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    afreehpLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: afreehp-log-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 25
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

# constructs 설정
constructs:
  website:
    type: server-side-website
    domain: afreehp.dochis.net
    certificate: arn:aws:acm:us-east-1:048901423835:certificate/a4b11e86-a541-4bae-bd2c-56cab6c0a7dc
    assets:
      '/app/**': public/app
      '/assets/**': public/assets

# custom 설정
custom:
  capacities:
    - table: afreehpLogTable
      read:
        minimum: 5
        maximum: 1000     # Maximum read capacity
        usage: 0.85
      write:
        minimum: 25
        maximum: 1000
        usage: 0.5

# package 설정
package:
  exclude:
    - .github/**
    - public/**