app:
  timeout: 10
  handler: handler/app.handler
  environment: ${file(.deploy/env/${opt:stage, self:provider.stage}.js)}
  events:
    - httpApi: '*'
connect:
  timeout: 10
  handler: handler/websocket.connect
  environment: ${file(.deploy/env/${opt:stage, self:provider.stage}.js)}
  events:
    - websocket:
        route: $connect
disconnect:
  timeout: 10
  handler: handler/websocket.disconnect
  environment: ${file(.deploy/env/${opt:stage, self:provider.stage}.js)}
  events:
    - websocket:
        route: $disconnect
message:
  timeout: 20
  handler: handler/websocket.message
  environment: ${file(.deploy/env/${opt:stage, self:provider.stage}.js)}
  events:
    - websocket:
        route: $default
logger:
  timeout: 5
  handler: handler/logger.handler
  environment: ${file(.deploy/env/${opt:stage, self:provider.stage}.js)}
  events:
    - cloudwatchLog:
        logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-app
        filter: '[timestamp=*Z, request_id="*-*", event]'
    - cloudwatchLog:
        logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-connect
        filter: '[timestamp=*Z, request_id="*-*", event]'
    - cloudwatchLog:
        logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-disconnect
        filter: '[timestamp=*Z, request_id="*-*", event]'
    - cloudwatchLog:
        logGroup: /aws/lambda/afreehp-api-${self:provider.stage}-message
        filter: '[timestamp=*Z, request_id="*-*", event]'