resources:
  Resources:
    afreehpTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: afreehp-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    afreehpLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: afreehp-log-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true